/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package q2_project;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Font;
import java.io.InputStream;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author Acer
 */
public class Automation extends javax.swing.JFrame {

    /**
     * Creates new form Automations
     */
    public Automation() {
        initComponents();
        try {
            InputStream pixelTTF = MainMenu.class.getResourceAsStream("fonts/DalekPinpoint.ttf");
            Font myFont = Font.createFont(Font.TRUETYPE_FONT, pixelTTF);
            backButton.setFont(myFont.deriveFont(20f));
            formulaButton.setFont(myFont.deriveFont(20f));
            solutionButton.setFont(myFont.deriveFont(20f));
            jTextField1.setFont(myFont.deriveFont(16f));
            jTextField2.setFont(myFont.deriveFont(16f));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void click_sound() {
        // Sound Credit: taken from Interface Sounds by Kenney
        // https://kenney.nl/assets/interface-sounds
        URL soundURL = getClass().getResource("/assets/click.aiff");
        try {
            AudioInputStream ais = AudioSystem.getAudioInputStream(soundURL);
            Clip clip = AudioSystem.getClip();  
            clip.open(ais);
            clip.start();
        } catch (Exception ex) {
        }
    }
    
    int a, b;
    boolean showFormula = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabelX = new javax.swing.JLabel();
        jLabelY = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jLabelH = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        formulaButton = new javax.swing.JButton();
        solutionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automation - CS4 Project");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 145, 40, 40));

        jTextField2.setBackground(new java.awt.Color(0,0,0,0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 202, 40, 40));

        submitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AUTOMATION_CHECKMARK.png"))); // NOI18N
        submitButton.setContentAreaFilled(false);
        submitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 120, 60));

        jLabelX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelX.setText("0");
        getContentPane().add(jLabelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 110, 40));

        jLabelY.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelY.setText("0");
        getContentPane().add(jLabelY, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 90, 40));

        jLabelC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelC.setText("0");
        getContentPane().add(jLabelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 235, 80, 40));

        jLabelH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelH.setText("0");
        getContentPane().add(jLabelH, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 120, 30));

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_Automation.png"))); // NOI18N
        backButton.setText("<< Back");
        backButton.setContentAreaFilled(false);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 120, 60));

        formulaButton.setBackground(new java.awt.Color(72, 133, 141));
        formulaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        formulaButton.setForeground(new java.awt.Color(255, 255, 255));
        formulaButton.setText("Formulas");
        formulaButton.setBorder(null);
        formulaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        formulaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        formulaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(formulaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 120, 50));

        solutionButton.setBackground(new java.awt.Color(72, 133, 141));
        solutionButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        solutionButton.setForeground(new java.awt.Color(255, 255, 255));
        solutionButton.setText("Show");
        solutionButton.setBorder(null);
        solutionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        solutionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(solutionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AUTOMATION_upscaled.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int[] sqrtize(int x) {
        int root = (int)Math.sqrt(x);
        for (int i = root; i > 1; i--) {
            if (x == (i*i)) {
                /* if the numbers are Pythagorean triples,
                output a single (whole number) value only */
                int[] outs = {i};
                return outs;
            }
            else if (x % (i*i) == 0) {
                /* the output array is in the format
                [coefficient, radicand] */
                int[] outs = {i, (x/(i*i))};
                return outs;
            }
        }
        // 'default' return statement if the coefficient is 1
        int[] outs = {1, x};
        return outs;
    }
    
    private int GCD(int a, int b){
        if (b==0) return a;
        return GCD(b,a%b);
    }
    
    private void updateOutputs(){
        int a2 = a*a;
        int b2 = b*b;
        int[] c = sqrtize(a2 + b2);
        if (c.length == 1) {
            jLabelC.setText(String.format("%d", c[0]));
            int gcd_x = GCD(a2, c[0]);
            jLabelX.setText(String.format("%1$d/%2$d", a2/gcd_x, c[0]/gcd_x));
            int gcd_y = GCD(b2, c[0]);
            jLabelY.setText(String.format("%1$d/%2$d", b2/gcd_x, c[0]/gcd_x));
            int gcd_h = GCD((a*b), c[0]);
            jLabelH.setText(String.format("%1$d/%2$d", (a*b)/gcd_x, c[0]/gcd_x));
        } 
        else {
            if (c[0] == 1) jLabelC.setText(String.format("√(%d)", c[1]));
            else jLabelC.setText(String.format("%1$d√(%2$d)", c[0], c[1]));
            int x_coeff = (a2/c[0]);
            jLabelX.setText(String.format("[%1$d√(%2$d)]/%2$d", x_coeff, c[1]));
            int y_coeff = (b2/c[0]);
            jLabelY.setText(String.format("[%1$d√(%2$d)]/%2$d", y_coeff, c[1]));
            int h_coeff = ((a*b)/c[0]);
            jLabelH.setText(String.format("[%1$d√(%2$d)]/%2$d", h_coeff, c[1]));
        }
    }
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        click_sound();
        a = Integer.parseInt(jTextField1.getText());
        b = Integer.parseInt(jTextField2.getText());
        updateOutputs();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        click_sound();
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void formulaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulaButtonActionPerformed
        click_sound();
        new Formulas().setVisible(true);
    }//GEN-LAST:event_formulaButtonActionPerformed

    private void solutionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionButtonActionPerformed
        click_sound();
        new Solutions(a,b,jLabelC.getText(),jLabelX.getText(),jLabelY.getText(),jLabelH.getText()).setVisible(true);
    }//GEN-LAST:event_solutionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Automation().setVisible(true);
                }
            });
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Automation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton formulaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelH;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton solutionButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
