/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package q2_project;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.InputStream;
import java.awt.Font;
import java.net.URL;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author Acer
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        try {
            InputStream pixelTTF = MainMenu.class.getResourceAsStream("fonts/DalekPinpoint.ttf");
            Font myFont = Font.createFont(Font.TRUETYPE_FONT, pixelTTF);
            gameButton.setFont(myFont.deriveFont(20f));
            automButton.setFont(myFont.deriveFont(16f));
            helpButton.setFont(myFont.deriveFont(20f));
            loopMusic();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loopMusic() {
        // Music credit: Melancholic Walk by Pix
        // https://youtu.be/dm4kGvOxmjE
        URL soundURL = getClass().getResource("/assets/melancholic.aiff");
        try {
            AudioInputStream ais = AudioSystem.getAudioInputStream(soundURL);
            Clip clip = AudioSystem.getClip();  
            clip.open(ais);
            clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } catch (Exception ex) {
        }
    }
    
    private void click_sound() {
        // Sound Credit: taken from Interface Sounds by Kenney
        // https://kenney.nl/assets/interface-sounds
        URL soundURL = getClass().getResource("/assets/click.aiff");
        try {
            AudioInputStream ais = AudioSystem.getAudioInputStream(soundURL);
            Clip clip = AudioSystem.getClip();  
            clip.open(ais);
            clip.start();
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpButton = new javax.swing.JButton();
        gameButton = new javax.swing.JButton();
        automButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CS4 Project (Bicbic, Rosalejos, Sitchon)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        helpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpButton.setForeground(new java.awt.Color(255, 255, 255));
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_Automation.png"))); // NOI18N
        helpButton.setText("HELP");
        helpButton.setContentAreaFilled(false);
        helpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 140, 60));

        gameButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gameButton.setForeground(new java.awt.Color(255, 255, 255));
        gameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_Game.png"))); // NOI18N
        gameButton.setText("GAME");
        gameButton.setContentAreaFilled(false);
        gameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 60));

        automButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        automButton.setForeground(new java.awt.Color(255, 255, 255));
        automButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_Automation.png"))); // NOI18N
        automButton.setText("AUTOMATION");
        automButton.setContentAreaFilled(false);
        automButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        automButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automButtonActionPerformed(evt);
            }
        });
        getContentPane().add(automButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_BG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        click_sound();
        dispose();
        new GameLevel().setVisible(true);
    }//GEN-LAST:event_gameButtonActionPerformed

    private void automButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automButtonActionPerformed
        click_sound();
        dispose();
        new Automation().setVisible(true);
    }//GEN-LAST:event_automButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        click_sound();
        new Help().setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MainMenu().setVisible(true);
                }
            });
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Automation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton automButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
