/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package q2_project;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Acer
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameButton = new javax.swing.JButton();
        automButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CS4 Project (Bicbic, Rosalejos, Sitchon)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gameButton.setForeground(new java.awt.Color(255, 255, 255));
        gameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_Game.png"))); // NOI18N
        gameButton.setText("GAME");
        gameButton.setContentAreaFilled(false);
        gameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 60));

        automButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        automButton.setForeground(new java.awt.Color(255, 255, 255));
        automButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_Automation.png"))); // NOI18N
        automButton.setText("AUTOMATION");
        automButton.setContentAreaFilled(false);
        automButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        automButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automButtonActionPerformed(evt);
            }
        });
        getContentPane().add(automButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/HOME_BG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        dispose();
        new GameLevel().setVisible(true);
    }//GEN-LAST:event_gameButtonActionPerformed

    private void automButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automButtonActionPerformed
        dispose();
        new Automation().setVisible(true);
    }//GEN-LAST:event_automButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatIntelliJLaf());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MainMenu().setVisible(true);
                }
            });
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Automation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton automButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
